### ISSUE TITLE
Hydration completed but contains mismatches

### ISSUE THREAD

**Issue by TohidMth** [xiCO2k/laravel-vue-i18n#193]
hi

Hello
When using this plugin in inertia
There is a hydration problem in SSR mode

In the following case
```
ssr.ts
.use(i18nVue, {
    lang: "fa",
    resolve: (lang) => {
        const langs = import.meta.glob("../../lang/*.json", { eager: true });
        return (langs[`../../lang/${lang}.json`] as any).default;
    },
})
```
Error: Hydration completed but contains mismatches

And in the following case
```
.use(i18nVue, {
    resolve: (lang) => {
        const langs = import.meta.glob("../../lang/*.json", { eager: true });
        return (langs[`../../lang/${lang}.json`] as any).default;
    },
})
```
The hydrated problem is solved. But the texts in the page source are not translated. and are displayed as follows:
messages.example ...

**Comment by DJDavid98** [comment]
I managed to solve this by using the `page.props` to pass down the locale from the app

**app/Http/Middleware/HandleInertiaRequests.php**
```php
  /**
   * Define the props that are shared by default.
   *
   * @return array<string, mixed>
   */
  public function share(Request $request):array {
    return [
      ...parent::share($request),
      'app' => [
        'locale' => App::getLocale(),
      ],
      // …
    ];
  }
```


**ssr.ts**
```ts
createServer((page) =>
  createInertiaApp({
    page,
    render: renderToString,
    title: (title) => title ? `${title} - ${appName}` : appName,
    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob<DefineComponent>('./Pages/**/*.vue')),
    setup({ App, props, plugin }) {
      return createSSRApp({ render: () => h(App, props) })
        .use(plugin)
        .use(ZiggyVue, {
          ...page.props.ziggy,
          location: new URL(page.props.ziggy.location),
        })
        .use(i18nVue, {
          // Set lang dynamically here
          lang: page.props.app.locale,
          fallbackLang: 'en',
          fallbackMissingTranslations: true,
          resolve: (lang: string) => {
            const langJsonImporters = import.meta.glob(`../../lang/php_*.json`, { eager: true });
            const result = langJsonImporters[`../../lang/php_${lang}.json`];
            return result.default;
          },
        });
    },
  }),
);
```

**Comment by SpeedJack** [comment]
> I managed to solve this by using the `page.props` to pass down the locale from the app

This solves the issue of having the correct translation loaded with SSR but does not solve the hydration mismatch.

The mismatch is caused by the async loading of the language. To solve, the app needs to be mounted *after* the language has been loaded (of course this comes at the cost of delaying the loading of the app). So:

**app/Http/Middleware/HandleInertiaRequests.php**
```php
namespace App\Http\Middleware;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Inertia\Middleware;

class HandleInertiaRequests extends Middleware
{
	/* ... */

	public function share(Request $request): array
	{
		return array_merge(parent::share($request), [
			'app' => [
				'locale' => App::getLocale(),
			],
		]);
	}
}
```

**resources/js/app.ts**
```ts
import '../css/app.css';
import './bootstrap';
import { createInertiaApp } from '@inertiajs/vue3';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import { createSSRApp, type DefineComponent, h } from 'vue';
import { i18nVue } from 'laravel-vue-i18n';

const appName = 'Laravel';

createInertiaApp({
	title: (title) => title ? `${title} - ${appName}` : `${appName}`,
	resolve: (name) => resolvePageComponent(
		`./Pages/${name}.vue`,
		import.meta.glob<DefineComponent>('./Pages/**/*.vue')
	),
	setup({ el, App, props, plugin }) {
		const app = createSSRApp({
			render: () => h(App, props),
		})
		.use(plugin)
		.use(i18nVue, {
			resolve: async lang => {
				const langs = import.meta.glob('../../lang/*.json');
				return await langs[`../../lang/${lang}.json`]();
			},
			onLoad: () => { /* mount app after language loading */
				if (el && el.__vue_app__) /* check needed to avoid remounting (which will fail) when we call loadLanguageAsync to change language */
					return;
				app.mount(el);
			}
		}); /* note that app is not mounted here anymore */
	},
});
```

**resources/js/ssr.ts**
```ts
import { createInertiaApp } from '@inertiajs/vue3';
import createServer from '@inertiajs/vue3/server';
import { renderToString } from '@vue/server-renderer';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import { createSSRApp, type DefineComponent, h } from 'vue';
import { i18nVue } from 'laravel-vue-i18n';

const appName = 'Laravel';

createServer((page) =>
	createInertiaApp({
		page,
		render: renderToString,
		title: (title) => title ? `${title} - ${appName}` : `${appName}`,
		resolve: (name) => resolvePageComponent(
			`./Pages/${name}.vue`,
			import.meta.glob<DefineComponent>('./Pages/**/*.vue')
		),
		setup({ App, props, plugin }) {
			return createSSRApp({ render: () => h(App, props) })
				.use(plugin)
				.use(i18nVue, {
					lang: page.props.app.locale, /* use correct language server-side */
					resolve: lang => {
						const langs = import.meta.glob('../../lang/*.json', { eager: true });
						return langs[`../../lang/${lang}.json`].default;
					},
				});
		},
	})
);
```

I think that this should be documented in the README.

**Comment by xiCO2k** [comment]
Can you send a PR adding that to the readme?

**Comment by MatLeRock** [comment]
I added this also, so it only mounts after full lang load:

```
...
let resolvedLangsCount = 0
let loadedLangsCount = 0

createInertiaApp({
...
    setup ({ el, App, props, plugin }) {
        const app = createApp({ render: () => h(App, props) })
            .use(i18nVue, {
                resolve: async lang => {
                    resolvedLangsCount++
                    const langs = import.meta.glob('../lang/*.json')
                    return await langs[`../lang/${lang}.json`]()
                },
                onLoad: () => {                  
                    if (el && el.__vue_app__) { return }

                    // mount when all langs have been loaded
                    loadedLangsCount++
                    if (loadedLangsCount === resolvedLangsCount) {
                        app.mount(el)
                    }
                }
...
```

**Comment by santigarcor** [comment]
@SpeedJack I'm using your code with Laravel Inertia and I'm getting this error:
```
app.ts:54 Uncaught (in promise) ReferenceError: Cannot access 'app' before initialization
    at Object.onLoad (app.ts:54:21)
    at I18n.setLanguage (laravel-vue-i18n.js?v=17abcb26:591:16)
    at I18n.loadLanguageAsync (laravel-vue-i18n.js?v=17abcb26:511:47)
    at I18n.load (laravel-vue-i18n.js?v=17abcb26:473:56)
    at I18n.setOptions (laravel-vue-i18n.js?v=17abcb26:466:23)
    at I18n.getSharedInstance (laravel-vue-i18n.js?v=17abcb26:673:26)
    at Object.install (laravel-vue-i18n.js?v=17abcb26:426:37)
    at Object.use (vue.runtime.esm-bundler-BoiyDnld.js?v=17abcb26:4477:13)
    at setup (app.ts:39:14)
```
